### ISSUE TITLE
404 error on downloading cover.jpg causing python to bail.

### ISSUE THREAD

**Issue by WildOne69** [IgnoredAmbience/yahoo-group-archiver#104]
MacOS Mojave 10.14.6

2019-11-07 18:11:33.869 PST INFO archive_links Written 23 links from  folder
2019-11-07 18:11:34.182 PST ERROR archive_calendar Couldn't download calendar/events: missing entityId
2019-11-07 18:11:34.494 PST INFO archive_about Downloading group description data
2019-11-07 18:11:34.805 PST INFO archive_about Downloading the photo in group description as GroupPhoto-853212.jpg
2019-11-07 18:11:35.543 PST INFO archive_about Downloading the group cover as GroupCover-cover.jpg
2019-11-07 18:11:35.989 PST ERROR YahooGroupsAPI Unknown 404 error for http://xa.yimg.com/kq/groups/mMTRmSbtfdIU2tTssA--/or/uFgghATtfNJ9IeCWxj0-/name/cover.jpg, giving up on this download
Traceback (most recent call last):
  File "./yahoo.py", line 727, in <module>
    archive_about(yga)
  File "./yahoo.py", line 454, in archive_about
    yga.download_file(photoinfo['displayURL'], f)
  File "/Users/me/yahoo-group-archiver/yahoogroupsapi.py", line 134, in download_file
    r.raise_for_status()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://xa.yimg.com/kq/groups/mMTRmSbtfdIU2tTssA--/or/uFgghATtfNJ9IeCWxj0-/name/cover.jpg

**Comment by d235j** [comment]
@onewildchild045 what's the group name?

**Comment by WildOne69** [comment]
@d235j IC2200

**Comment by IgnoredAmbience** [comment]
Group does not appear to have a cover photo. Latest version of code seems to handle this gracefully.
