### ISSUE TITLE
How do I use this script?

### ISSUE THREAD

**Issue by Squidconqueror** [IgnoredAmbience/yahoo-group-archiver#17]
I'm trying to use it to archive files for an old game before Yahoo shuts down Groups but the instructions were unclear and very confusing to me.
![Yahoo Group Archiver Error](https://user-images.githubusercontent.com/56778771/67153957-ae149700-f2b8-11e9-8fb5-a862d82c35d9.jpg)

**Comment by cas206** [comment]
Those instructions are for Linux.

**Comment by rigr** [comment]
In Windows: Have you installed Python? if yes, download the zip using the green button "Clone or download" and choose "download zip". unzip, next open a cmd window, cd to the directory the files were unzipped to. Now start the yahoo.py using the right -u and -p and so on values. You might need to "py pip install requests", too.
Hope that helps

**Comment by Squidconqueror** [comment]
Thanks for the help. When I tried the commands I got a -u and -p is not recognized as an internal or external command,operable program or batch file and '"py pip install requests"' is not recognized as an internal or external command,operable program or batch file error. It this still doesn't work I guess I'll have to download them the old fashion way because I'm getting closer and closer to the deadline. As a matter of fact I should get started asap while I still have the chance. If there's a mistake or error that I had made please let me know.
![Yahoo Group Archiver Error 2](https://user-images.githubusercontent.com/56778771/67164441-31c59680-f340-11e9-9e0c-a1bdc9bb8170.jpg)

**Comment by rigr** [comment]
try 'pip install requests' without py in front. The command then works for me to download the messages.

![yahooarch](https://user-images.githubusercontent.com/6568315/67164700-cdc1c300-f37d-11e9-889d-acab1ec876d3.png)

**Comment by Squidconqueror** [comment]
C:\Users\wgame\Desktop\yahoo-group-archiver>'pip install requests'
''pip' is not recognized as an internal or external command,
operable program or batch file. I should note that i'm using cmd for the command and I don't know how to setup Python to run the script.

**Comment by rigr** [comment]
- no quotes, just like in the image shown. so:
C:\Users\wgame\Desktop\yahoo-group-archiver>pip install requests
and try 
C:\Users\wgame\Desktop\yahoo-group-archiver>yahoo.py
without the pip command first, then try the pip command. 
You will also need the cookie-values.

**Comment by Squidconqueror** [comment]
I got C:\Users\wgame\Desktop\yahoo-group-archiver>yahoo.py
Traceback (most recent call last):
  File "C:\Users\wgame\Desktop\yahoo-group-archiver\yahoo.py", line 2, in <module>
    from yahoogroupsapi import YahooGroupsAPI
  File "C:\Users\wgame\Desktop\yahoo-group-archiver\yahoogroupsapi.py", line 1, in <module>
    import requests
ImportError: No module named requests
and C:\Users\wgame\Desktop\yahoo-group-archiver>install requests
'install' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cozykettle** [comment]
I'm having similar problems. I thought I had requests installed because every time I've run the pip install command since it says the requirement already been satisfied.  However when I run: 

> C:\Users\User\Downloads\yahoo-group-archiver-master\yahoo-group-archiver-master\yahoo.py -u "_username@gmail.com_" -ct "_superlongTvalue_" -cy "_superlonYvalue_" "_groupid_"

all I get in return is:

> Traceback (most recent call last):
  File "C:\Users\User\Downloads\yahoo-group-archiver-master\yahoo-group-archiver-master\yahoo.py", line 2, in <module>
    from yahoogroupsapi import YahooGroupsAPI
  File "C:\Users\User\Downloads\yahoo-group-archiver-master\yahoo-group-archiver-master\yahoogroupsapi.py", line 1, in <module>
    import requests
ImportError: No module named requests

So apparently it can't find requests
I'm a super noob at this of course so I'm just curious what I might be doing that's so dumb.

**Comment by dossy** [comment]
@camwow13 what do you get from the command `echo %PATH%` ?  Perhaps you have multiple versions of Python installed, and the version that you installed `pip` for is different than the first Python installation in your `%PATH%` ...

**Comment by cozykettle** [comment]
@dossy I get this:

> C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Program Files\AdoptOpenJDK\jre-11.0.4.11-hotspot\bin;C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\PuTTY\;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\Program Files\Calibre2\;
C:\Users\User\AppData\Local\Microsoft\WindowsApps;
C:\PortableApps\youtube-dl;
C:\PortableApps\ffmpeg\bin;;
C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin

I don't think I'm seeing what I'm supposed to see here, but I do think you're right. I installed Python a while back with a Ninite installer and it put 2.7 for some reason instead of 3. I installed Python 3 today. Something has gummed up the works. You think I should just go scorched earth and uninstall everything and start fresh?

In any case I actually got this script running. I just used WSL instead with the Ubuntu command line. It fired up first try 🤷‍♂️

**Comment by aplarsen** [comment]
I'm a heavy user of Python 3, so I had to get 2.7 working to use this script.  Here are the steps I followed on Win 10:

- Download and install [Python 2.7](https://www.python.org/download/releases/2.7/).  I installed it to c:\program files\Python27.
- Download [get-pip.py](https://bootstrap.pypa.io/get-pip.py) and save it to c:\program files\Python27\Tools\Scripts\
- In an elevated command prompt (right-click Command Prompt in Start menu and click Run As Administrator.
- cd into the Scripts folder `cd 'c:\program files\Python27\Tools\Scripts'`
- Install pip `..\..\python get-pip.py`
- cd to your Python folder `cd 'c:\program files\Python27'`
- Install requests `python -m pip install requests`
- cd to the location you unzipped the yahoo-group-archiver repository
- Run the script `'c:\program files\Python27\python' yahoo.py -ct "<T_cookie>" -cy "<Y_cookie>" "<groupid>"` per the [documentation](https://github.com/IgnoredAmbience/yahoo-group-archiver)

Hope this helps someone.  There are going to be a lot of Python noobs trying to run this in the next couple of days as people scramble to get groups archived before Yahoo shuts down the hosting.

**Comment by rigr** [comment]
thank you! finally that worked.

**Comment by ugcheleuce** [comment]
FWIW (Windows 10):
1. When installing Python 2.7 on Windows, near the end of the installation process, the option to add Python to the PATH is deselected.  Make sure you select that option.
2. In my case, the installer attempted to install at C:\Python27\ instead of "program files".  This is not a bad idea, because it makes it easier to write some of the BAT files (if any).
3. In my case, I was able to use the scripts by creating two BAT files in the folder with the scripts, namely:

FILE1.bat
python -m pip install --upgrade pip
pip install -r "requirements.txt"

FILE2.bat
python ./yahoo.py -ct "TCOOKIEHERE" -cy "YCOOKIEHERE" "GROUPNAMEHERE"

**Comment by dsolap** [comment]
Hello I use macos terminal but says after ./yahoo.py -ct "TCOOKIEHERE" -cy "YCOOKIEHERE" "GROUPNAMEHERE"
 Traceback (most recent call last):
  File "./yahoo.py", line 3, in <module>
    import yahoogroupsapi
  File "/Users/didi/yahoo-group-archiver-master/yahoogroupsapi.py", line 17, in <module>
    import requests  # Must be imported after capture_http
ImportError: No module named requests
MacBook-Pro-de-Diana:yahoo-group-archiver-master didi$ 
I have been strugling with this for two days!

**Comment by aairfccha** [comment]
> Hello I use macos terminal but says after ./yahoo.py -ct "TCOOKIEHERE" -cy "YCOOKIEHERE" "GROUPNAMEHERE"
>[...]
> ImportError: No module named requests
> MacBook-Pro-de-Diana:yahoo-group-archiver-master didi$
> I have been strugling with this for two days!

Looks like something went wrong at the pip install step, requests is one of the modules which should be installed there. Have you tried the original command with single quotes (')? This thread is rather skewed towards Windows whereas MacOS (which you seem to run) is quite unixoid.

Going back to Windows and in addition to the comments from ugcheleuce and aplarsen: The option for automatically adding Python to PATH also exists in the Python 3 installer, you just have to do an install with customised options. And if you install Python in the "proper" location for software, you might need to run cmd with administrator rights to install packages.
