### ISSUE TITLE
Encoding error in logger line on windows

### ISSUE THREAD

**Issue by IgnoredAmbience** [IgnoredAmbience/yahoo-group-archiver#85]
```2019-10-30 15:27:52.842 Eastern Daylight Time INFO archive_db Downloading database table '常见问题' (1/1)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 90-93: character maps to <undefined>
Call stack:
  File "yahoo.py", line 791, in <module>
    archive_db(yga)
  File "yahoo.py", line 374, in archive_db
    logger.info("Downloading database table '%s' (%d/%d)", table['name'], n, nts)
Message: "Downloading database table '%s' (%d/%d)"
Arguments: ('常见问题', 1, 1)
```

Added table of same name to `archive-test`
Unable to reproduce on linux

**Comment by IgnoredAmbience** [comment]
I think this might be fixed in master.
