### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Sadi58** [IgnoredAmbience/yahoo-group-archiver#89]
Thanks a lot for working on this!
However, after following all the steps carefully, I've got the error message below in Linux Mint:
```
Traceback (most recent call last):
  File "./yahoo.py", line 3, in <module>
    from yahoogroupsapi import YahooGroupsAPI
  File "./yahoogroupsapi.py", line 14, in <module>
    import requests  # Must be imported after capture_http
ImportError: No module named requests
```
Any ideas?

**Comment by Pablo2m** [comment]
Try executing this in the console:
"pip install requests"
(without the quotes)

**Comment by Sadi58** [comment]
@Pablo2m Thank you, it worked!
